### ISSUE TITLE
FileNotFoundError: cannot find the reference SRT data

### ISSUE THREAD

**Issue by duohongrui** [Chunfu-Shawn/STellaris-Analysis-Pipeline#1]
Hi, STellaris provides an effective way for users to map scRNA-seq cells onto the corresponding SRT data. However, it seems that some reference SRT datasets cannot be found according to the original paths you set. I used the scRNA-seq data derived from liver in mouse, but the matched SRT dataset `STW-M-Liver-Visium-1` cannot be successfully opened. Here are the error messages:
```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/user/data3/uplee/projects/spatialTransWeb/spatial/visualization/STW-M-Liver-Visium-1/GSM5764417/GSM5764417.input.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Run `reticulate::py_last_error()` for details.

Calls: read_st ... <Anonymous> -> py_to_r_ifneedbe -> <Anonymous> -> py_call_impl

Execution halted

Sun Apr 7 03:07:58 UTC 2024 Spatial mapping failed for some reason, please check log files!
```
Could you please check it out and fix the problem? Thanks so much.

**Comment by Chunfu-Shawn** [comment]
Have fixed this bug, and now you can run the spatial mapping function normally. thanks!
