### ISSUE TITLE
Problems when mapping with CellTrek

### ISSUE THREAD

**Issue by Fred-Evif** [Chunfu-Shawn/STellaris-Analysis-Pipeline#3]
![屏幕截图 2024-10-14 195635](https://github.com/user-attachments/assets/8692e5eb-473a-4180-81d1-2849f7b8b512)

The error log shows:

Error: package or namespace load failed for ‘Seurat’:

object 'integral' not found whilst loading namespace 'spatstat.core'

Execution halted

Mon Oct 14 12:05:07 UTC 2024 Spatial mapping failed for some reason, please check log files!

Even running with your examples by click the "Run Example" on your website.
You should update the packages I think.
额好像不用说英文来着哈哈

试了下，另外两个方法也不行，都报这个错

**Comment by Chunfu-Shawn** [comment]
> 行

Thanks a lot! I have fixed the issue.
谢谢，应该是我更新了其他包导致的问题，哈哈哈哈

**Comment by Chunfu-Shawn** [comment]
> ![屏幕截图 2024-10-14 195635](https://private-user-images.githubusercontent.com/71593073/376231677-8692e5eb-473a-4180-81d1-2849f7b8b512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDk2MjIsIm5iZiI6MTcyODkwOTMyMiwicGF0aCI6Ii83MTU5MzA3My8zNzYyMzE2NzctODY5MmU1ZWItNDczYS00MTgwLTgxZDEtMjg0OWY3YjhiNTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEyMzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNmYwYWQwNzVlMDViZTUxMmE0M2Q2N2MyZDI2NDUzZDQ1ZDgxMThjZjRkZTE1MjA3YzVlY2FmNWRiODYzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cRVP5a9PczTXGYAHcNeF71B0xwUv1joFZUgF8seQaRc)
> 
> The error log shows:
> 
> Error: package or namespace load failed for ‘Seurat’:
> 
> object 'integral' not found whilst loading namespace 'spatstat.core'
> 
> Execution halted
> 
> Mon Oct 14 12:05:07 UTC 2024 Spatial mapping failed for some reason, please check log files!
> 
> Even running with your examples by click the "Run Example" on your website. You should update the packages I think. 额好像不用说英文来着哈哈
> 
> 试了下，另外两个方法也不行，都报这个错

Thanks a lot! I have fixed the issue.
谢谢，应该是我更新了其他包导致的问题，哈哈哈哈

**Comment by Fred-Evif** [comment]
ok，不过刚刚试了下还是不行，可能是没刷新好，我明天试试看

**Comment by Fred-Evif** [comment]
确实已经能跑了，至少example可以，但是有个新问题是我今天一次都没有上传数据集成功过，同样的数据集，昨天还能的，刷新网页也没用，不停在upload unsuccessful，有什么头绪或者解决方案吗

**Comment by Chunfu-Shawn** [comment]
> 确实已经能跑了，至少example可以，但是有个新问题是我今天一次都没有上传数据集成功过，同样的数据集，昨天还能的，刷新网页也没用，不停在upload unsuccessful，有什么头绪或者解决方案吗

我这边可以上传诶，你试着关掉代理和梯子？STellaris如果识别网络不正常或者像是机器人，会禁止上传数据

**Comment by Fred-Evif** [comment]
没开梯子和代理，不过可能是我人在国外的原因，而且刚刚还连着实验室的服务器，服务器现在关掉了，刚刚终于成功了！
